export const FRONTEND_URL = {
    LOGIN: "/",
    AGENT_LOGIN: "/auth/login/agent",
    SUPERAGENT_LOGIN: "/auth/login/superagent",
    AUTH_LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    AGENT_REGISTER: "/auth/register/agent",
    INDIVIDUAL_REGISTER: "/auth/register/individual",
    SUPERAGENT_REGISTER: "/auth/register/superagent",
    VERIFY_ACCOUNT: "/auth/verify-account",
    VERIFY_CONFIRMATION: "/auth/verify-confirmation",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_CONFIRMATION: "/auth/reset-confirmation",
    NEW_PASSWORD: "/auth/reset-password",
    DASHBOARD: "/dashboard",
}